trigger:
- master
- rel/*

variables: 
  BuildConfiguration: Release
  
steps:
- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables

- task: NuGetToolInstaller@0
  displayName: Use NuGet 4.6.2
  inputs:
    versionSpec: 4.6.2

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: build/setversion.csproj
    arguments: -c $(BuildConfiguration)   
  displayName: Set Version

- powershell: .\build\build.ps1 -target=Package
  displayName: Build 
#  env:
#    SignClientSecret: $(SignClientSecret)
#    SignClientUser: $(SignClientUser)
    

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: .\Microsoft.Toolkit.Uwp.SampleApp.Wasm\bin\Release\netstandard2.0\dist
    artifactType: container
    artifactName: Wasm

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: .\bin\nupkg
    artifactType: container
    artifactName: WCT-Packages
  condition: always()
